export const SERVICE_CATEGORIES = {
  'Web Development': {
    label: 'Web Development',
    icon: '🌐',
    color: 'from-blue-500 to-cyan-500',
    fields: [
      { name: 'pages', label: 'Number of Pages', type: 'number', placeholder: 'e.g., 5', section: 'Technical Specs' },
      { name: 'seo', label: 'SEO Optimization', type: 'checkbox', section: 'Technical Specs' },
      { name: 'ssl', label: 'SSL Certificate', type: 'checkbox', section: 'Technical Specs' },
      { name: 'speed', label: 'Performance Speed Target', type: 'text', placeholder: 'e.g., < 2s', section: 'Technical Specs' },
      { name: 'responsive', label: 'Responsive Design', type: 'checkbox', section: 'Technical Specs' },
      { name: 'hosting', label: 'Hosting Included (Months)', type: 'number', placeholder: 'e.g., 12', section: 'Support & Hosting' },
      { name: 'support', label: 'Support Duration (Months)', type: 'number', placeholder: 'e.g., 6', section: 'Support & Hosting' },
      { name: 'maintenance', label: 'Free Maintenance (Months)', type: 'number', placeholder: 'e.g., 3', section: 'Support & Hosting' },
      { name: 'timeline', label: 'Delivery Timeline', type: 'text', placeholder: 'e.g., 4 weeks', section: 'Timeline' },
      { name: 'revisions', label: 'Revision Rounds', type: 'number', placeholder: 'e.g., 3', section: 'Timeline' },
    ],
  },
  'Mobile App Development': {
    label: 'Mobile App Development',
    icon: '📱',
    color: 'from-purple-500 to-pink-500',
    fields: [
      { name: 'platform', label: 'Platform', type: 'multiselect', options: ['Android', 'iOS', 'Cross-Platform'], section: 'Platform' },
      { name: 'features', label: 'Number of Core Features', type: 'number', placeholder: 'e.g., 10', section: 'Features' },
      { name: 'screens', label: 'Number of Screens', type: 'number', placeholder: 'e.g., 20', section: 'Features' },
      { name: 'uiux', label: 'UI/UX Design Included', type: 'checkbox', section: 'Design' },
      { name: 'appStore', label: 'App Store Submission', type: 'checkbox', section: 'Deployment' },
      { name: 'api', label: 'Backend API Development', type: 'checkbox', section: 'Backend' },
      { name: 'database', label: 'Database Setup', type: 'checkbox', section: 'Backend' },
      { name: 'maintenance', label: 'Maintenance Plan (Months)', type: 'number', placeholder: 'e.g., 6', section: 'Support' },
      { name: 'support', label: 'Support Duration (Months)', type: 'number', placeholder: 'e.g., 12', section: 'Support' },
      { name: 'timeline', label: 'Development Timeline', type: 'text', placeholder: 'e.g., 3 months', section: 'Timeline' },
      { name: 'revisions', label: 'Revision Rounds', type: 'number', placeholder: 'e.g., 5', section: 'Timeline' },
    ],
  },
  'Digital Marketing': {
    label: 'Digital Marketing',
    icon: '📊',
    color: 'from-green-500 to-emerald-500',
    fields: [
      { name: 'type', label: 'Campaign Type', type: 'multiselect', options: ['SEO', 'Google Ads', 'Content Marketing', 'Email Marketing', 'Retargeting'], section: 'Campaign Type' },
      { name: 'budget', label: 'Monthly Ad Budget (₹)', type: 'number', placeholder: 'e.g., 50000', section: 'Budget' },
      { name: 'keywords', label: 'Number of Keywords', type: 'number', placeholder: 'e.g., 20', section: 'Keywords' },
      { name: 'reporting', label: 'Monthly Reports', type: 'checkbox', section: 'Reporting' },
      { name: 'metrics', label: 'Performance Metrics Tracking', type: 'checkbox', section: 'Reporting' },
      { name: 'analytics', label: 'Google Analytics Setup', type: 'checkbox', section: 'Analytics' },
      { name: 'optimization', label: 'Campaign Optimization', type: 'checkbox', section: 'Optimization' },
      { name: 'ctr', label: 'Target CTR (%)', type: 'number', placeholder: 'e.g., 3.5', section: 'Targets' },
      { name: 'roi', label: 'Target ROI (%)', type: 'number', placeholder: 'e.g., 300', section: 'Targets' },
      { name: 'timeline', label: 'Campaign Duration (Months)', type: 'number', placeholder: 'e.g., 3', section: 'Timeline' },
    ],
  },
  'Social Media Marketing': {
    label: 'Social Media Marketing',
    icon: '📱',
    color: 'from-pink-500 to-rose-500',
    fields: [
      { name: 'platforms', label: 'Platforms', type: 'multiselect', options: ['Facebook', 'Instagram', 'LinkedIn', 'Twitter', 'TikTok', 'YouTube'], section: 'Platforms' },
      { name: 'postsPerWeek', label: 'Posts Per Week', type: 'number', placeholder: 'e.g., 5', section: 'Content' },
      { name: 'contentCalendar', label: 'Content Calendar', type: 'checkbox', section: 'Content' },
      { name: 'contentCreation', label: 'Content Creation Included', type: 'checkbox', section: 'Content' },
      { name: 'engagement', label: 'Engagement Management', type: 'checkbox', section: 'Management' },
      { name: 'communityMgmt', label: 'Community Management', type: 'checkbox', section: 'Management' },
      { name: 'reports', label: 'Monthly Performance Reports', type: 'checkbox', section: 'Reporting' },
      { name: 'analytics', label: 'Analytics & Insights', type: 'checkbox', section: 'Reporting' },
      { name: 'adSpend', label: 'Monthly Ad Spend (₹)', type: 'number', placeholder: 'e.g., 30000', section: 'Budget' },
      { name: 'timeline', label: 'Campaign Duration (Months)', type: 'number', placeholder: 'e.g., 6', section: 'Timeline' },
    ],
  },
  'Lead Generation': {
    label: 'Lead Generation',
    icon: '🎯',
    color: 'from-orange-500 to-red-500',
    fields: [
      { name: 'campaignType', label: 'Campaign Platform', type: 'multiselect', options: ['Facebook Ads', 'Google Ads', 'Landing Page', 'LinkedIn Ads', 'Email Marketing'], section: 'Campaign Setup' },
      { name: 'targetLeads', label: 'Target Leads', type: 'number', placeholder: 'e.g., 100', section: 'Targets' },
      { name: 'cpl', label: 'Cost Per Lead (₹)', type: 'number', placeholder: 'e.g., 500', section: 'Pricing' },
      { name: 'leadQuality', label: 'Lead Quality Score (1-10)', type: 'number', placeholder: 'e.g., 8', section: 'Quality' },
      { name: 'leadTracking', label: 'Lead Funnel Tracking', type: 'checkbox', section: 'Tracking' },
      { name: 'crmIntegration', label: 'CRM Integration', type: 'checkbox', section: 'Integration' },
      { name: 'automation', label: 'Lead Nurturing Automation', type: 'checkbox', section: 'Automation' },
      { name: 'reporting', label: 'Weekly Lead Reports', type: 'checkbox', section: 'Reporting' },
      { name: 'optimization', label: 'Continuous Optimization', type: 'checkbox', section: 'Optimization' },
      { name: 'timeline', label: 'Campaign Duration (Months)', type: 'number', placeholder: 'e.g., 2', section: 'Timeline' },
    ],
  },
  'UI/UX Design': {
    label: 'UI/UX Design',
    icon: '🎨',
    color: 'from-indigo-500 to-purple-500',
    fields: [
      { name: 'designType', label: 'Design Scope', type: 'select', options: ['Web Design', 'App Design', 'Branding', 'Complete Redesign', 'Design System'], section: 'Scope' },
      { name: 'screens', label: 'Number of Screens/Pages', type: 'number', placeholder: 'e.g., 15', section: 'Deliverables' },
      { name: 'wireframes', label: 'Wireframes Included', type: 'checkbox', section: 'Deliverables' },
      { name: 'prototype', label: 'Interactive Prototype', type: 'checkbox', section: 'Deliverables' },
      { name: 'designSystem', label: 'Design System Included', type: 'checkbox', section: 'Deliverables' },
      { name: 'userResearch', label: 'User Research Included', type: 'checkbox', section: 'Research' },
      { name: 'usability', label: 'Usability Testing', type: 'checkbox', section: 'Testing' },
      { name: 'accessibility', label: 'WCAG Accessibility Compliance', type: 'checkbox', section: 'Compliance' },
      { name: 'revisions', label: 'Revision Rounds', type: 'number', placeholder: 'e.g., 3', section: 'Process' },
      { name: 'timeline', label: 'Delivery Timeline', type: 'text', placeholder: 'e.g., 3 weeks', section: 'Timeline' },
    ],
  },
  'E-commerce Solutions': {
    label: 'E-commerce Solutions',
    icon: '🛒',
    color: 'from-yellow-500 to-orange-500',
    fields: [
      { name: 'platform', label: 'E-commerce Platform', type: 'select', options: ['Shopify', 'WooCommerce', 'Custom', 'Multi-vendor', 'Magento'], section: 'Platform' },
      { name: 'products', label: 'Number of Products', type: 'number', placeholder: 'e.g., 100', section: 'Store Setup' },
      { name: 'categories', label: 'Number of Categories', type: 'number', placeholder: 'e.g., 10', section: 'Store Setup' },
      { name: 'paymentGateways', label: 'Payment Gateways', type: 'number', placeholder: 'e.g., 3', section: 'Payments' },
      { name: 'inventory', label: 'Inventory Management', type: 'checkbox', section: 'Management' },
      { name: 'analytics', label: 'Sales Analytics Dashboard', type: 'checkbox', section: 'Analytics' },
      { name: 'seo', label: 'SEO Optimization', type: 'checkbox', section: 'Optimization' },
      { name: 'shipping', label: 'Shipping Integration', type: 'checkbox', section: 'Integration' },
      { name: 'support', label: 'Support Duration (Months)', type: 'number', placeholder: 'e.g., 6', section: 'Support' },
      { name: 'timeline', label: 'Setup Timeline', type: 'text', placeholder: 'e.g., 4 weeks', section: 'Timeline' },
    ],
  },
  'Branding & Logo Design': {
    label: 'Branding & Logo Design',
    icon: '✨',
    color: 'from-violet-500 to-fuchsia-500',
    fields: [
      { name: 'packageType', label: 'Package Type', type: 'select', options: ['Logo Only', 'Full Branding', 'Rebranding', 'Complete Identity', 'Brand Refresh'], section: 'Package' },
      { name: 'logoVariations', label: 'Logo Variations', type: 'number', placeholder: 'e.g., 5', section: 'Logo' },
      { name: 'logoFormats', label: 'Logo File Formats', type: 'multiselect', options: ['PNG', 'SVG', 'PDF', 'AI', 'EPS'], section: 'Logo' },
      { name: 'brandGuide', label: 'Brand Guidelines Document', type: 'checkbox', section: 'Documentation' },
      { name: 'colorPalette', label: 'Color Palette & Typography', type: 'checkbox', section: 'Documentation' },
      { name: 'brandStory', label: 'Brand Story & Messaging', type: 'checkbox', section: 'Documentation' },
      { name: 'collateral', label: 'Marketing Collateral (Business Cards, etc)', type: 'checkbox', section: 'Collateral' },
      { name: 'socialTemplates', label: 'Social Media Templates', type: 'checkbox', section: 'Collateral' },
      { name: 'revisions', label: 'Revision Rounds', type: 'number', placeholder: 'e.g., 3', section: 'Process' },
      { name: 'timeline', label: 'Delivery Timeline', type: 'text', placeholder: 'e.g., 2 weeks', section: 'Timeline' },
    ],
  },
};

export const CATEGORY_LIST = Object.keys(SERVICE_CATEGORIES);
